// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "1252dafc-07b0-4121-9e57-3a35fb7f1fd5";

const char SSID[]     = "farm";    // Network SSID (name)
const char PASS[]     = "12345678";    // Network password (use for WPA, or use as key for WEP)


float inner_temperature;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(inner_temperature, READ, 300 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
